platform :ios, '11.0'
use_frameworks!

target 'DownTube' do
  pod 'XCDYouTubeKit'
  pod 'MMWormhole'
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'DownTubeShareExtension' do
  pod 'MMWormhole'
end

target 'DownTubeUITests' do

end

